task_list/task_list/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls', namespace='tasks'))
]

task_list/tasks/urls.py
from django.urls import path
from .views import task_list, create_task, create_category, delete_task, complete_task

app_name = 'tasks'

urlpatterns = [
    path('', task_list, name='task_list'),
    path('create/', create_task, name='create_task'),
    path('complete/<int:task_id>/', complete_task, name='complete_task'),
    path('delete/<int:task_id>/', delete_task, name='delete_task'),
    path('create_category/', create_category, name='create_category')
]

task_list/tasks/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Category(models.Model):
    title = models.CharField(
        max_length=100,
        verbose_name='Название категории'
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Уникальный элемент категории'
    )

    def __str__(self):
        return self.title

class Task(models.Model):
    title = models.CharField(
        max_length=50,
        verbose_name='Название задачи',
        help_text='Введите название задачи'
    )
    author = models.CharField(
        max_length=50
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        related_name='tasks',
        blank=True,
        null=True,
        verbose_name='Категория',
        help_text='Категория для задачи'
    )
    description = models.TextField(
        verbose_name='Описание задачи'
    )
    deadline = models.DateTimeField(
        verbose_name='Срок выполнения'
    )
    completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

task_list/tasks/forms.py
from django import forms
from .models import Task, Category

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'author', 'category', 'description', 'deadline']

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['title', 'slug']

task_list/tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import TaskForm, CategoryForm
from .models import Task

def create_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('tasks:task_list')
    else:
        form = TaskForm()
    return render(request, 'tasks/create_task.html', {'form': form})

def task_list(request):
    tasks = Task.objects.all()
    return render(request, 'tasks/task_list.html', {'tasks': tasks})

def create_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('tasks:task_list')
    else:
        form = CategoryForm()
    return render(request, 'tasks/create_category.html', {'form': form})

def complete_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    task.completed = True
    task.save()
    return redirect('tasks:task_list')

def delete_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    task.delete()
    return redirect('tasks:task_list')

task_list/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <title>My Task List</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" type="text/css">
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Task List</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'tasks:task_list' %}">Tasks</a>
          </li>
          {% comment %} <li class="nav-item">
            <a class="nav-link" href="{% url 'tasks:category_list' %}">Categories</a>
          </li> {% endcomment %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'tasks:create_task' %}">Create Task</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'tasks:create_category' %}">Create Category</a>
          </li>
        </ul>
      </div>
    </nav>
  </header>

  <main class="container mt-4">
    {% block content %}
    {% endblock %}
  </main>

  <footer class="bg-light text-center py-3 fixed-bottom">
    &copy; 2023 My Task List. All rights reserved.
  </footer>


  <!-- Подключение скриптов Bootstrap -->
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>


task_list/templates/tasks/create_category.html
{% extends 'base.html' %}
{% block content %}
<h1>Create Category</h1>

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Create</button>
</form>
{% endblock %}

task_list/templates/tasks/create_task.html
{% extends 'base.html' %}
{% block content %}
<h1>Create Task</h1>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Create</button>
</form>
{% endblock %}

task_list/templates/tasks/task_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Task List</h1>
  <div class="create-buttons">
    <a href="{% url 'tasks:create_task' %}" class="btn btn-primary">Create Task</a>
    <a href="{% url 'tasks:create_category' %}" class="btn btn-primary">Create Category</a>
  </div>

  <div class="row mt-4">
    {% for task in tasks %}
      <div class="col-md-4 mb-4">
        <div class="task-block {% if task.completed %}completed{% elif task.deadline < now %}overdue{% else %}in-progress{% endif %} p-3 h-100 d-flex flex-column"> 
          <h3 class="text-center mb-3">{{ task.title }}</h3>
          <div class="flex-grow-1">
            <p>Category: {{ task.category }}</p>
            <p>Description: {{ task.description }}</p>
            <p>Deadline: {{ task.deadline }}</p>
            <p>Author: {{ task.author }}</p>
            <p>Created at: {{ task.created_at }}</p>
            <p>Completed: {{ task.completed }}</p>
          </div>
          <div class="button-group mt-2">
            <form action="{% url 'tasks:complete_task' task.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn btn-primary">Change Status</button>
            </form>
            <form action="{% url 'tasks:delete_task' task.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger">Delete Task</button>
            </form>
          </div>
        </div>
      </div>
      {% cycle '' '' '</div><div class="row mt-4">' %}
    {% empty %}
      <p>No tasks found.</p>
    {% endfor %}
  </div>
{% endblock %}